/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module Lut(a, b, clk, reset, s, sync, out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  input [4:0] a;
  wire [4:0] a;
  input [4:0] b;
  wire [4:0] b;
  input clk;
  wire clk;
  output [4:0] out;
  wire [4:0] out;
  input reset;
  wire reset;
  input [1:0] s;
  wire [1:0] s;
  input sync;
  wire sync;
  sky130_fd_sc_hd__clkinv_1 _060_ (
    .A(a[1]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _061_ (
    .A(b[3]),
    .B(a[3]),
    .Y(_006_)
  );
  sky130_fd_sc_hd__xor2_1 _062_ (
    .A(b[3]),
    .B(a[3]),
    .X(_007_)
  );
  sky130_fd_sc_hd__nand2b_1 _063_ (
    .A_N(b[2]),
    .B(a[2]),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _064_ (
    .A(b[2]),
    .B(a[2]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__xor2_1 _065_ (
    .A(b[2]),
    .B(a[2]),
    .X(_010_)
  );
  sky130_fd_sc_hd__nand2_1 _066_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _067_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _068_ (
    .A(_011_),
    .SLEEP(_012_),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _069_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__xnor2_1 _070_ (
    .A(b[0]),
    .B(a[0]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _071_ (
    .A(b[0]),
    .SLEEP(a[0]),
    .X(_016_)
  );
  sky130_fd_sc_hd__maj3_1 _072_ (
    .A(b[1]),
    .B(_005_),
    .C(_016_),
    .X(_017_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _073_ (
    .A(_010_),
    .SLEEP(_017_),
    .X(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _074_ (
    .A1(_008_),
    .A2(_018_),
    .B1(_007_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__and2_0 _075_ (
    .A(s[0]),
    .B(s[1]),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand3_1 _076_ (
    .A(_007_),
    .B(_008_),
    .C(_018_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand3b_1 _077_ (
    .A_N(_019_),
    .B(_020_),
    .C(_021_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__o21ai_0 _078_ (
    .A1(_012_),
    .A2(_014_),
    .B1(_011_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__maj3_1 _079_ (
    .A(b[2]),
    .B(a[2]),
    .C(_023_),
    .X(_024_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _080_ (
    .A(s[1]),
    .SLEEP(s[0]),
    .X(_025_)
  );
  sky130_fd_sc_hd__xor2_1 _081_ (
    .A(_007_),
    .B(_024_),
    .X(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _082_ (
    .A1(b[3]),
    .A2(a[3]),
    .B1(s[0]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o31ai_1 _083_ (
    .A1(s[1]),
    .A2(_006_),
    .A3(_027_),
    .B1(sync),
    .Y(_028_)
  );
  sky130_fd_sc_hd__a21oi_1 _084_ (
    .A1(_025_),
    .A2(_026_),
    .B1(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__nor2_1 _085_ (
    .A(sync),
    .B(out[3]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a211oi_1 _086_ (
    .A1(_022_),
    .A2(_029_),
    .B1(_030_),
    .C1(reset),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _087_ (
    .A(_010_),
    .B(_017_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__o21ai_0 _088_ (
    .A1(_010_),
    .A2(_023_),
    .B1(_025_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__a21oi_1 _089_ (
    .A1(_010_),
    .A2(_023_),
    .B1(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a21oi_1 _090_ (
    .A1(b[2]),
    .A2(a[2]),
    .B1(s[0]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__o31ai_1 _091_ (
    .A1(s[1]),
    .A2(_009_),
    .A3(_034_),
    .B1(sync),
    .Y(_035_)
  );
  sky130_fd_sc_hd__a311oi_1 _092_ (
    .A1(_018_),
    .A2(_020_),
    .A3(_031_),
    .B1(_033_),
    .C1(_035_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _093_ (
    .A(sync),
    .B(out[2]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor3_1 _094_ (
    .A(reset),
    .B(_036_),
    .C(_037_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__o21ai_0 _095_ (
    .A1(_013_),
    .A2(_016_),
    .B1(_020_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a21oi_1 _096_ (
    .A1(_013_),
    .A2(_016_),
    .B1(_038_),
    .Y(_039_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(_013_),
    .B(_014_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__a21oi_1 _098_ (
    .A1(b[1]),
    .A2(a[1]),
    .B1(s[0]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__o31ai_1 _099_ (
    .A1(s[1]),
    .A2(_012_),
    .A3(_041_),
    .B1(sync),
    .Y(_042_)
  );
  sky130_fd_sc_hd__a211oi_1 _100_ (
    .A1(_025_),
    .A2(_040_),
    .B1(_042_),
    .C1(_039_),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor2_1 _101_ (
    .A(sync),
    .B(out[1]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__nor3_1 _102_ (
    .A(reset),
    .B(_043_),
    .C(_044_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor2_1 _103_ (
    .A(s[0]),
    .B(s[1]),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _104_ (
    .A(sync),
    .B(out[0]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__o221a_1 _105_ (
    .A1(s[1]),
    .A2(_014_),
    .B1(_015_),
    .B2(_045_),
    .C1(sync),
    .X(_047_)
  );
  sky130_fd_sc_hd__nor3_1 _106_ (
    .A(reset),
    .B(_046_),
    .C(_047_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor2_1 _107_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__xnor2_1 _108_ (
    .A(b[4]),
    .B(a[4]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _109_ (
    .A(a[3]),
    .SLEEP(b[3]),
    .X(_050_)
  );
  sky130_fd_sc_hd__nor3_1 _110_ (
    .A(_019_),
    .B(_049_),
    .C(_050_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__o21ai_0 _111_ (
    .A1(_019_),
    .A2(_050_),
    .B1(_049_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand3b_1 _112_ (
    .A_N(_051_),
    .B(_052_),
    .C(_020_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__maj3_1 _113_ (
    .A(b[3]),
    .B(a[3]),
    .C(_024_),
    .X(_054_)
  );
  sky130_fd_sc_hd__xnor2_1 _114_ (
    .A(_049_),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__a21oi_1 _115_ (
    .A1(b[4]),
    .A2(a[4]),
    .B1(s[0]),
    .Y(_056_)
  );
  sky130_fd_sc_hd__o31ai_1 _116_ (
    .A1(s[1]),
    .A2(_048_),
    .A3(_056_),
    .B1(sync),
    .Y(_057_)
  );
  sky130_fd_sc_hd__a21oi_1 _117_ (
    .A1(_025_),
    .A2(_055_),
    .B1(_057_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _118_ (
    .A(out[4]),
    .B(sync),
    .Y(_059_)
  );
  sky130_fd_sc_hd__a211oi_1 _119_ (
    .A1(_053_),
    .A2(_058_),
    .B1(_059_),
    .C1(reset),
    .Y(_004_)
  );
  sky130_fd_sc_hd__dfxtp_1 _120_ (
    .CLK(clk),
    .D(_003_),
    .Q(out[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _121_ (
    .CLK(clk),
    .D(_002_),
    .Q(out[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _122_ (
    .CLK(clk),
    .D(_001_),
    .Q(out[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _123_ (
    .CLK(clk),
    .D(_000_),
    .Q(out[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _124_ (
    .CLK(clk),
    .D(_004_),
    .Q(out[4])
  );
endmodule
